# Translations template for keystone.
# Copyright (C) 2014 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: Keystone\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2014-06-26 06:01+0000\n"
"PO-Revision-Date: 2014-06-20 20:11+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: English (United Kingdom) (http://www.transifex.com/projects/p/"
"keystone/language/en_GB/)\n"
"Language: en_GB\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: keystone/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "Original exception being dropped: %s"

#: keystone/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "Unexpected exception occurred %d time(s)... retrying."

#: keystone/openstack/common/lockutils.py:120
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr "Could not release the acquired lock `%s`"

#: keystone/openstack/common/loopingcall.py:89
msgid "in fixed duration looping call"
msgstr "in fixed duration looping call"

#: keystone/openstack/common/loopingcall.py:131
msgid "in dynamic looping call"
msgstr "in dynamic looping call"

#: keystone/openstack/common/policy.py:511
#, python-format
msgid "Failed to understand rule %s"
msgstr "Failed to understand rule %s"

#: keystone/openstack/common/policy.py:521
#, python-format
msgid "No handler for matches of kind %s"
msgstr "No handler for matches of kind %s"

#: keystone/openstack/common/policy.py:791
#, python-format
msgid "Failed to understand rule %r"
msgstr "Failed to understand rule %r"

#: keystone/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "Exception during rpc cleanup."

#: keystone/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr "Unhandled exception"
